// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plkdxzobwznazcamqzvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsa2R4em9id3puYXpjYW1xenZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MjcwMDgsImV4cCI6MjA3MDIwMzAwOH0.hOOmeVAQPJw6cuQAktWjFMZOQJTANdHQ-K3wY2WR0zo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});